version: "3.9" 
services:
    frontend:
        build: ./frontend
        ports:
        - 3000:3000
        volumes:
            - ./frontend/src:/usr/src/app/src
    backend:
        build: ./backend
        ports:
        - 8000:8000
        volumes:
            - ./backend/src:/usr/src/app/src